# Generated by Django 6.1.1 on 2026-09-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_book_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='book_category_idx'),
        ),
    ]
